#!/bin/bash
make clean
make
cd build

make tests/vm/pt-grow-stack.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-grow-bad.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-big-stk-obj.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-bad-addr.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-bad-read.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-write-code.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-write-code2.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/pt-grow-stk-sc.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-linear.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-parallel.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-merge-seq.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-merge-par.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-merge-stk.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-merge-mm.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/page-shuffle.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-read.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-close.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-unmap.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-overlap.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-twice.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-write.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-exit.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-shuffle.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-bad-fd.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-clean.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-inherit.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-misalign.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-null.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-over-code.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-over-data.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-over-stk.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-remove.result VERBOSE=1 | grep 'pass test\|FAIL test'
make tests/vm/mmap-zero.result VERBOSE=1 | grep 'pass test\|FAIL test'
